### ISSUE TITLE
Added java code for Next Greater Element 

### ISSUE THREAD

**Issue by Yuktikashyap** [TecHAyusH6476/Interview-Prep-DSA-HacktoberFest-2023#15]
Heyy @TecHAyusH6476 this is a very famous problem - Next Greater Element 
I will be solving this problem using Stacks
Kindly assign this to be as a part of Hactoberfest2023.I will be solving this in JAVA language.
Thanks

**Comment by TecHAyusH6476** [comment]
@Yuktikashyap Assigned 👍 
Create a PR and Merge it in main branch

**Comment by Yuktikashyap** [comment]
Done.

**Comment by TecHAyusH6476** [comment]
@Yuktikashyap Now check your profile

**Comment by Yuktikashyap** [comment]
Its not working - still showing same thing - excluded
Thanks for helping me 😢

**Comment by TecHAyusH6476** [comment]
@Yuktikashyap I see,  might be repo is excluded now because I have merged all PRs at once
[https://github.com/fineanmol/hacktoberfest](https://github.com/fineanmol/hacktoberfest)
Try on this one it worked for me 😄

**Comment by Yuktikashyap** [comment]
Thank you so so much 😊

I will contribute in this repo
BTW can I make all 3 pr here or can u plz share some more repo like this if
pos 😅

**Comment by TecHAyusH6476** [comment]
@Yuktikashyap You can create 4 PRs in same repo but on safer side create few on other repos as well
[https://github.com/Saikat2407/DSA_Hacktoberfest2023](https://github.com/Saikat2407/DSA_Hacktoberfest2023)
[https://github.com/zero-to-mastery/file-io](https://github.com/zero-to-mastery/file-io)
Here are few which will accept PR quickly

**Comment by Yuktikashyap** [comment]
FineAlmon repo - was also excluded
I will try doing in others

Now I am feeling why is this happening 😞 excluded excluded again n again

BTW thank you so much for helping me 😊🍦

**Comment by TecHAyusH6476** [comment]
@Yuktikashyap idk maybe admins are more strict this year in including selected repos to Hacktober fest, try on others
yeah np 👍

**Comment by Yuktikashyap** [comment]
Hi is it happening with me only that my pr are getting excluded or is it
happening with everyone
As i am still not able to resolve the issue that's why i am asking you
If you can help or tell me anything which i can do - It would be a
great help😥

**Comment by TecHAyusH6476** [comment]
@Yuktikashyap No thats only when repo gets excluded not only your PR is rejected cuz I created on one of repos I shared got accepted last week
Can share your PR links I will check whats the issue?

**Comment by TecHAyusH6476** [comment]
[https://github.com/zero-to-mastery/file-io/pull/154](https://github.com/zero-to-mastery/file-io/pull/154)
For ref: this is one of PRs got accepted

**Comment by Yuktikashyap** [comment]
Wow ur pr is really good 😃

As for my pr I have made some pr in your repo which got excluded and in way
I made pr in other repo - they also got excluded
😟

PlZ help if pos

**Comment by TecHAyusH6476** [comment]
@Yuktikashyap Sure just share your PR link so that I can check what can be updated
Or I can show you how to pass PR in google meet if u want

**Comment by Yuktikashyap** [comment]
Thanks for helping 🌸
See if this works - https://github.com/simranlotey/programs/pull/274

Can u plz tell some LinkedIn profile or something where I can connect with
you and u can tell me a way to resolve it

**Comment by TecHAyusH6476** [comment]
Sure I will check PR 👍 
[https://www.linkedin.com/in/ayush-singh-6476ofc/](https://www.linkedin.com/in/ayush-singh-6476ofc/)
here you can connect on linkedin

**Comment by TecHAyusH6476** [comment]
`🚀 Hi maintainers, @l-white 
I'm thrilled to submit this PR as part of Hacktoberfest 2023! 🎉

With this PR, I've enhanced the Spotify Data Analysis script, streamlining the data processing and incorporating better visualization techniques. Here's a quick rundown:

🎵 Created the SpotifyDataAnalyzer class for more modular and organized code.
📊 Introduced histogram visualization for BPM distribution to provide clearer insights.
🔍 Optimized data loading and processing for efficiency.

I've thoroughly tested the changes, and everything seems to be working smoothly. Would love your feedback and, if everything looks good, hope this can be merged soon!
**(Please use hacktober accepted tag)**


Happy Hacktoberfest! 🍁🎃`

**Comment by TecHAyusH6476** [comment]
`import pandas as pd
import matplotlib.pyplot as plt

class SpotifyDataAnalyzer:

    def __init__(self, file_name='spotify-2023.csv'):
        # Load the data from the given CSV file using pandas
        self.data = pd.read_csv(file_name, encoding='latin-1')

    def number_of_songs(self):
        """Return the total number of songs in the dataset."""
        return self.data.shape[0]

    def common_artist(self):
        """Return the list of most common artists in the dataset."""
        return self.data['artist(s)_name'].mode().tolist()

    def visualize_bpm_distribution(self):
        """Plot the distribution of song tempos (BPM) using a histogram."""
        plt.hist(self.data['bpm'], bins=10, edgecolor='k')
        plt.title('BPM Distribution')
        plt.xlabel('BPM (Tempo)')
        plt.ylabel('Frequency')
        plt.show()

if __name__ == "__main__":
    analyzer = SpotifyDataAnalyzer()

    print(f"The total number of songs in the playlist: {analyzer.number_of_songs()}")
    print(f"The most common artists occuring in the playlist: {analyzer.common_artist()}")
    analyzer.visualize_bpm_distribution()`

**Comment by TecHAyusH6476** [comment]
/spotify_data_analysis.py - File name
