### ISSUE TITLE
Edit Distance (Dyanmic Programming)

### ISSUE THREAD

**Issue by sdas2k3** [TecHAyusH6476/Interview-Prep-DSA-HacktoberFest-2023#4]
Heyy @TecHAyusH6476  this is a very famous problem from LeetCode based on Dynamic Programming.
Link : https://leetcode.com/problems/edit-distance/description/
Kindly assign this to be as a part of Hactoberfest2023.I will be solving this in C++ language.
Thanks

**Comment by adit2005** [comment]
Hey @TecHAyusH6476  I would like to work on this problem and would give the best optimized soln. Kindly assign me this.
I will be solving in C++.

**Comment by TecHAyusH6476** [comment]
@adit2005 Assigned you the issue 
Make sure to check conflicts

**Comment by adit2005** [comment]
@TecHAyusH6476 can u please tell in which folder should i add my code??

**Comment by TecHAyusH6476** [comment]
@adit2005 In DP folder there is already a folder for dynamic programming
Also I am thinking to create sub-folders for each topic so that cpp,python and java code could be separated

**Comment by adit2005** [comment]
Thanks @TecHAyusH6476 for telling.

**Comment by TecHAyusH6476** [comment]
@adit2005 @sdas2k3 Please pick this sub folder issue after adding and I will add you both as contributors so you can accepted other people PRs
Happy HackSept Fest 🚀 🚀

**Comment by adit2005** [comment]
ok @TecHAyusH6476 will do it.
