### ISSUE TITLE
Course Schedule (Topo Sort)

### ISSUE THREAD

**Issue by sdas2k3** [TecHAyusH6476/Interview-Prep-DSA-HacktoberFest-2023#5]
Heyy @TecHAyusH6476  this is a very famous problem from LeetCode based on Topo Sort Algorithm.
Link : https://leetcode.com/problems/course-schedule-ii/description/
Kindly assign this to be as a part of Hactoberfest2023.I will be solving this in C++ language.
Thanks

**Comment by TecHAyusH6476** [comment]
@sdas2k3 Assigned

**Comment by parasjain123** [comment]
Please review my PR for the above issue
